Table result using mu-sql-table-rendered class
mumuki/mumuki-sqlite-runner pull request #21
Opened 2018-02-13 22:53 UTC by leandrojdl

Now both result tables (success & error) uses `mu-sql-table-rendered-class` as discussed in #19 

I could not see it in a browser, I just changed html and some stuff in rendered.

I also added the possibility to use the key _result_alias_ in YAML test to define table name.

2018-02-14 17:15 UTC, leandrojdl commented
@flbulgarelli Travis is failing with this:

```
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......................................................
The job exceeded the maximum time limit for jobs, and has been terminated.
```

I don't know why

2018-02-14 20:01 UTC, flbulgarelli commented
> @flbulgarelli Travis is failing with this

Fixed

2018-02-15 17:20 UTC, fedescarpa commented
Buenas, lo probé y renderiza bien cuando la consulta es correcta :muscle: 

![image](https://user-images.githubusercontent.com/1039278/36270593-d87f2126-125a-11e8-81bb-d7fdd397b6c3.png)

Lo que noté es que cuando la consulta difiere la tabla de obtenido se ve mal (pero la del esperado sí se ve bien)

![image](https://user-images.githubusercontent.com/1039278/36270639-fda7c066-125a-11e8-9dea-adc9dff5c8f7.png)

Y este caso no se cuando es, creo que se da cuando tiene menos columnas que las esperadas, habría que chekearlo

![image](https://user-images.githubusercontent.com/1039278/36270667-108dcee6-125b-11e8-9d29-dbc949f2c475.png)

2018-02-15 17:20 UTC, fedescarpa requested changes
Por lo que mencioné antes

2018-02-15 17:58 UTC, leandrojdl commented
Ahí lo vi, me olvidé de ponerle la _class_ `mu-sql-table-rendered-class` a la tabla del obtenido, en cuanto esté en casa lo corrijo.

Por otro lado @fedescarpa , yo dejé estos estilos

```css
.required {
  color: #5cb85c;
  font-style: italic;
}
.errored {
  color: #d9534f;
  font-style: italic;
}
```

para cuando tiene que marcar las diferencias... te parecen bien así o los harías de otra manera?

2018-02-15 18:47 UTC, fedescarpa commented
Sisi, los vi y me parece bien :+1:

2018-02-22 15:41 UTC, fedescarpa commented
Ahora se renderiza bien la tabla pero en el caso que haya diferencias algunas celdas tienen distinta cantidad de columnas

![image](https://user-images.githubusercontent.com/1039278/36547697-36fb42bc-17cd-11e8-99f3-710d123a78b8.png)

Tal vez deberíamos hacer que si hay diferencias, todas las filas tengan la columna al principio con el `+` el `-` o vacía, no?

2018-02-22 21:13 UTC, fedescarpa commented
Ahí fixié mis propios comentarios. Péguenle una revisada al código @flbulgarelli y @leandrojdl, si les parece bien creo que ya está para mergear.

![image](https://user-images.githubusercontent.com/1039278/36564402-fc7a21ba-17fb-11e8-919f-24f52c531f69.png)

2018-02-22 21:13 UTC, fedescarpa approved these changes

2018-02-23 00:32 UTC, leandrojdl commented
Ok por mi @fedescarpa :smiley:

2018-02-23 14:19 UTC, fedescarpa commented
Genial, 

Antes de mergear agregue un `✓` para las filas que están bien. ¿Qué opinan? Si les parece comiteo el cambio ese que lo tengo local y lo mergeamos, si no les convence lo mergeamos ahora.

![image](https://user-images.githubusercontent.com/1039278/36598512-292be254-188b-11e8-9f4b-07eb664d7981.png)

2018-02-23 14:24 UTC, NadiaFinzi commented
Buenísimo lo del tilde. Me parece más claro así qué está bien, qué sobra y qué falta 😃

2018-02-23 15:24 UTC, leandrojdl commented
Genial!!

2018-02-23 18:16 UTC, merged

2018-02-27 16:04 UTC, NadiaFinzi commented
Estuvimos discutiendo con @flbulgarelli sobre el color verde para las filas que sobran. Quizás sea más acorde usar amarillo, o algún otro color que haga referencia al error y, a la vez, al "excedente".